c_hopper.init("Curve Hopper",4,2,1,energy,[],null,[0,0]);
c_adder.init("Adder",2,1,2,blood,[s_death_touch],null,[1,0]);
c_automaton.init("Automaton",2,1,1,energy,[],null,[2,0]);
c_banshee.init("Banshee",1,1,1,bones,[s_flying],null,[3,0]);
c_energy_bot.init("Energy Bot",2,0,1,energy,[s_energy],null,[4,0]);
c_bloodhound.init("Bloodhound",2,2,4,blood,[s_guardian],null,[5,0]);
c_bolthound.init("Bolthound",5,2,3,energy,[s_guardian],null,[0,1]);
c_explode_bot.init("Explode Bot",4,1,1,energy,[s_explosive],null,[1,1]);
c_mrs_bomb.init("Mrs. Bomb",5,5,5,energy,[s_bomb],null,[2,1]);
c_bonehound.init("Bonehound",4,2,4,bones,[s_guardian],null,[3,1]);
c_bullfrog.init("Bullfrog",1,1,2,blood,[s_reach],null,[6,1]);
c_sniper.init("Sniper Bot",3,1,1,energy,[s_sniper],null,[8,1]);
c_cat.init("Cat",1,0,1,blood,[s_free_sac],null,[0,2]);
c_coyote.init("Coyote",2,1,3,bones,[],null,[0,3]);
c_pharaoh.init("Pharaoh's Pets",5,0,1,bones,[s_free_sac,s_worthy],null,[2,3]);
c_draugr.init("Draugr",1,0,2,bones,[s_frozen_skele,s_cant_be_sacced],null,[3,3]);
c_drowned.init("Drowned Soul",4,1,1,bones,[s_aquatic,s_death_touch],null,[4,3]);
c_elk.init("Elk",2,2,4,blood,[s_sidestep],null,[5,3]);
c_elk_fawn.init("Elk Fawn",1,1,1,blood,[s_elk_fawn,s_sidestep],null,[6,3]);
c_family.init("The Walkers",4,1,3,bones,[s_bones],null,[2,4]);
c_mice.init("Field Mice",2,2,2,blood,[s_fecundity],null,[3,4]);
c_frank_stein.init("Frank & Stein",3,2,2,bones,[],null,[7,4]);
c_ghost_ship.init("Ghost Ship",3,0,1,bones,[s_skele_spawner,s_aquatic],null,[2,5]);
c_gravedigger.init("Gravedigger",2,0,3,bones,[s_digger],null,[3,5]);
c_grizzly.init("Grizzly",3,4,5,blood,[],null,[6,5]);
c_gunner.init("Double Gunner",6,2,1,energy,[s_bifurcated],null,[7,5]);
c_hawk.init("Hawk",2,3,1,blood,[s_flying],null,[0,6]);
c_hrokkall.init("Hrokkall",1,1,1,blood,[s_aquatic,s_energy],null,[2,6]);
c_insectodrone.init("Insectodrone",3,1,2,energy,[s_flying],null,[3,6]);
c_kingfisher.init("Kingfisher",1,1,1,blood,[s_flying,s_aquatic],null,[6,6]);
c_squirrel_ball.init("Squirrel Ball",1,1,1,blood,[s_sq_spawner],null,[8,6]);
c_l33pbot.init("L33pbot",1,0,2,energy,[s_reach],null,[0,7]);
c_magpie.init("Magpie",2,1,1,blood,[s_flying,s_tutor],null,[2,7]);
// mantis god
// meat bot
c_49er.init("49er",2,1,1,energy,[s_sidestep],null,[2,8]);
c_mole.init("Mole",1,0,5,blood,[s_burrow],null,[3,8]);
c_mole_man.init("Mole Man",1,0,4,blood,[s_burrow,s_reach],null,[4,8]);
c_steambot.init("Steambot",6,3,2,energy,[],null,[8,8]);
c_mummy_lord.init("Mummy Lord",5,3,4,bones,[],null,[4,9]);
c_necromancer.init("Necromancer",3,1,2,bones,[s_double_death],null,[6,9]);
c_ouroboros.init("Ouroboros",2,1,1,blood,[s_ouroboros],null,[2,10]);
c_rabbit.init("Rabbit",0,0,1,bones,[],null,[5,10],false);
c_raven.init("Raven",2,2,3,blood,[s_flying],null,[6,10]);
c_revenant.init("Revenant",2,3,1,bones,[s_brittle],null,[7,10]);
c_stoat.init("Stoat",1,1,3,blood,[],null,[8,10]);
c_steel_mice.init("Steel Mice",6,1,2,energy,[s_fecundity],null,[0,11]);
c_salmon.init("Salmon",2,2,2,blood,[s_aquatic,s_sidestep],null,[2,11]);
c_sarcophagus.init("Sarcophagus",3,0,3,bones,[s_sarc],null,[3,11]);
c_thicc.init("Thick Droid",4,1,3,energy,[],null,[8,11]);
c_477.init("Urayuli",4,7,7,blood,[],null,[1,12]);
c_warren.init("Warren",1,0,3,blood,[s_rabbit],null,[2,12]);
c_wolf.init("Wolf",2,3,2,blood,[],null,[3,12]);
// wolf cub
c_zombie.init("Zombie",1,1,1,bones,[],null,[5,12]);
c_cockroach.init("Cockroach",3,1,1,bones,[s_undying],null,[8,12]);
c_bat.init("Bat",3,2,1,bones,[s_flying],null,[0,13]);
c_beaver.init("Beaver",2,1,4,blood,[s_dam],null,[1,13]);
c_dam.init("Dam",0,0,2,bones,[s_reach,s_cant_be_sacced],null,[2,13],false);
c_bee.init("Bee",0,1,1,bones,[s_flying],null,[3,13],false);
c_beehive.init("Beehive",1,0,2,blood,[s_beehive],null,[4,13]);
c_black_goat.init("Black Goat",2,0,4,blood,[s_worthy],null,[5,13]);
// child 13
c_daus.init("The Daus",2,2,1,blood,[s_bells],null,[7,13]);
c_bell.init("Bell",0,0,1,blood,[s_cant_be_sacced],null,[8,13],false);
c_dire_wolf.init("Dire Wolf",3,2,4,blood,[s_extra_attack],null,[1,14]);
c_rat_king.init("Rat King",2,2,1,blood,[s_bones],null,[2,14]);
c_raven_egg.init("Raven Egg",1,0,2,blood,[s_raven_egg],null,[3,14]);
c_alpha.init("Alpha",4,1,3,bones,[s_alpha],null,[4,14]);
c_mantis.init("Mantis",1,1,1,blood,[s_bifurcated],null,[5,14]);
c_moose_buck.init("Moose Buck",3,3,7,blood,[s_push],null,[6,14]);
c_skunk.init("Skunk",1,0,3,blood,[s_stinky],null,[7,14]);
c_great_white.init("Great White",3,4,2,blood,[s_aquatic],null,[8,14]);
c_porcupine.init("Porcupine",1,1,2,blood,[s_quills],null,[0,15]);
// pronghorn
c_rattler.init("Rattler",4,3,2,bones,[],null,[2,15]);
c_river_snapper.init("River Snapper",2,1,7,blood,[],null,[3,15]);
c_sparrow.init("Sparrow",1,1,2,blood,[s_flying],null,[4,15]);
// strange larva
c_vulture.init("Turkey Vulture",6,3,5,bones,[s_flying],null,[7,15]);
c_bone_horn.init("Bone Lord's Horn",6,1,1,bones,[],a_bone_horn,[4,1]);
c_tomb_raider.init("Tomb Robber",1,0,1,bones,[],a_disentomb,[0,12]);
c_plasma.init("Plasma Jimmy",3,0,3,energy,[],a_energy_gun,[0,4]);
c_bone_heap.init("Bone Heap",1,0,2,bones,[],a_enlarge,[5,1]);
c_hand_tent.init("Hand Tentacle",2,0,3,blood,[s_hand],null,[8,3]);
c_mirror_tent.init("Mirror Tentacle",1,0,4,blood,[s_mirror],null,[8,4]);